export const guestListData = {
  guests: [
    {
      id: '111',
      firstName: 'Mock',
      lastName: 'Data',
      address1: null,
      address2: null,
      city: null,
      state: null,
      zipCode: null,
      country: null,
      phone: null,
      email: null,
      notes: null,
      userId: '123',
      rsvps: [
        {
          eventId: '123456787',
          rsvp: 'Not Invited',
        },
        {
          eventId: '123456788',
          rsvp: 'Invited',
        },
        {
          eventId: '123456789',
          rsvp: 'Not Invited',
        },
      ],
    },
    {
      id: '222',
      firstName: 'Mock2',
      lastName: 'Data2',
      address1: null,
      address2: null,
      city: null,
      state: null,
      zipCode: null,
      country: null,
      phone: null,
      email: null,
      notes: null,
      userId: '123',
      rsvps: [
        {
          eventId: '123456787',
          rsvp: 'Attending',
        },
        {
          eventId: '123456788',
          rsvp: 'Attending',
        },
        {
          eventId: '123456789',
          rsvp: 'Declined',
        },
      ],
    },
    {
      id: '333',
      firstName: 'Mock3',
      lastName: 'Data3',
      address1: null,
      address2: null,
      city: null,
      state: null,
      zipCode: null,
      country: null,
      phone: null,
      email: null,
      notes: null,
      userId: '123',
      rsvps: [
        {
          eventId: '123456787',
          rsvp: 'Not Invited',
        },
        {
          eventId: '123456788',
          rsvp: 'Invited',
        },
        {
          eventId: '123456789',
          rsvp: 'Invited',
        },
      ],
    },
    {
      id: '444',
      firstName: 'Different',
      lastName: 'Events',
      address1: null,
      address2: null,
      city: null,
      state: null,
      zipCode: null,
      country: null,
      phone: null,
      email: null,
      notes: null,
      userId: '123',
      rsvps: [
        {
          eventId: '987654321',
          rsvp: 'Invited',
        },
        {
          eventId: '98765432',
          rsvp: 'Invited',
        },
        {
          eventId: '123456789',
          rsvp: 'Attending',
        },
      ],
    },
  ],
  events: [
    {
      id: '123456787',
      name: 'Mock Event 1',
      date: null,
      startTime: null,
      endTime: null,
      venue: null,
      attire: null,
      description: null,
      userId: '123',
    },
    {
      id: '123456788',
      name: 'Mock Event 2',
      date: null,
      startTime: null,
      endTime: null,
      venue: null,
      attire: null,
      description: null,
      userId: '123',
    },
    {
      id: '123456789',
      name: 'Mock Event 3',
      date: null,
      startTime: null,
      endTime: null,
      venue: null,
      attire: null,
      description: null,
      userId: '123',
    },
  ],
};
